config/routes.rb
Commonconcept::Application.routes.draw do

  match '/join',    :to => 'mingle/people#new'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/',        :to => 'pages#home'
 
  match '/think',   :to => 'pages#think'
  match '/mingle',  :to => 'pages#mingle'
  match '/make',    :to => 'pages#make' 

  namespace :mingle do
    resources :people
  end
 

  root :to => 'pages#home'

end

app/models/person.rb
class Person < ActiveRecord::Base
  # :name, :surname, :email

  has_many :thoughts
end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/models/thought.rb
class Thought < ActiveRecord::Base
  # :content
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mingle/people_controller.rb
class Mingle::PeopleController < ApplicationController

  # join the common - groups/clubs/gangs membership defined elsewhere
  def new
    @title = "Be Involved"        
  end

  
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def think
    @title = "Think"
  end
 
#  def mingle
#    @title = "Mingle"
#  end

  def make 
    @title = "Make"
  end

  # def help
  # @title = "Help"
  # end

end

app/controllers/stuff_controller.rb
class StuffController < ApplicationController
  # GET /stuff
  # GET /stuff.json
  def index
    @stuff = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stuff }
    end
  end

  # GET /stuff/1
  # GET /stuff/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /stuff/new
  # GET /stuff/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /stuff/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /stuff
  # POST /stuff.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stuff/1
  # PUT /stuff/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuff/1
  # DELETE /stuff/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to stuff_url }
      format.json { head :ok }
    end
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thoughts }
    end
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
    @thought = Thought.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thought }
    end
  end

  # GET /thoughts/new
  # GET /thoughts/new.json
  def new
    @thought = Thought.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thought }
    end
  end

  # GET /thoughts/1/edit
  def edit
    @thought = Thought.find(params[:id])
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = Thought.new(params[:thought])

    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render json: @thought, status: :created, location: @thought }
      else
        format.html { render action: "new" }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thoughts/1
  # PUT /thoughts/1.json
  def update
    @thought = Thought.find(params[:id])

    respond_to do |format|
      if @thought.update_attributes(params[:thought])
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought = Thought.find(params[:id])
    @thought.destroy

    respond_to do |format|
      format.html { redirect_to thoughts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Common Concept"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/mingle/people_helper.rb
module Mingle::PeopleHelper
end

app/helpers/mingle_helper.rb
module MingleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stuff_helper.rb
module StuffHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Think", think_path %></li>
      <li><%= link_to "Mingle", mingle_path %></li>
      <li><%= link_to "Make", make_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo_banner.png", :alt => "Common Concept", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round"> 
    <ul>
      <li><%= link_to "Think", 'think_path' %> </li>
      <li><%= link_to "Mingle", 'mingle_path' %> </li>
      <li><%= link_to "Make", 'make_path' %> </li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">

      <%= render 'layouts/header' %>

      <div class="padding"> &nbsp; <br />  </div>

      <section class="round">
        <%= yield %>
      </section>

      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/mingle/people/join.html.erb
<h1>Mingle::People#new</h1>
<p>Find me in app/views/mingle/people/new.html.erb</p>

app/views/mingle/people/new.html.erb
<h1>Mingle::People#new</h1>
<p>Find me in app/views/mingle/people/new.html.erb</p>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Let's play with me!</h1>
<p>It's like you are at a cafe smoking gauloises and stabbing at the tattered pages of your latest screen play with a tooth scarred # 2; or a cocktail lounge hobknobbing with industry types trying desperately to impress each other with how unimpressable they are. </p>

<%= link_to "Join the conversation!", join_path, :class => "join_button round" %>


 

app/views/stuff/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :substance %><br />
    <%= f.text_field :substance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stuff/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', stuff_path %>

app/views/stuff/index.html.erb
<h1>Listing stuff</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Substance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stuff.each do |thing| %>
  <tr>
    <td><%= thing.name %></td>
    <td><%= thing.description %></td>
    <td><%= thing.substance %></td>
    <td><%= link_to 'Show', thing %></td>
    <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
    <td><%= link_to 'Destroy', thing, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thing', new_thing_path %>

app/views/stuff/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', stuff_path %>

app/views/stuff/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @thing.name %>
</p>

<p>
  <b>Description:</b>
  <%= @thing.description %>
</p>

<p>
  <b>Substance:</b>
  <%= @thing.substance %>
</p>


<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', stuff_path %>

app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>
  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing thought</h1>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<h1>Listing thoughts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @thoughts.each do |thought| %>
  <tr>
    <td><%= thought.content %></td>
    <td><%= thought.person_id %></td>
    <td><%= link_to 'Show', thought %></td>
    <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
    <td><%= link_to 'Destroy', thought, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thought', new_thought_path %>

app/views/thoughts/new.html.erb
<h1>New thought</h1>

<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @thought.content %>
</p>

<p>
  <b>Person:</b>
  <%= @thought.person_id %>
</p>


<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>